app:
  container_name: iris-website
  build: ./
  volumes:
    - ./:/var/www
  links:
    - redis
  ports:
    - 3003:3003
  environment:
    - NODE_ENV=development
    - PORT=3003
  command:
    sh -c 'npm i && npm run ${PLATFORM}'
